(()=>{'use strict';const C=MICore,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],cv={d2:$('#c2d'),d3:$('#c3d'),s2:$('#c2s'),s3:$('#c3s')};const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),D=d=>d*Math.PI/180,R=r=>r*180/Math.PI,V=(x,y,z)=>({x,y,z}),add=(a,b)=>V(a.x+b.x,a.y+b.y,a.z+b.z),sub=(a,b)=>V(a.x-b.x,a.y-b.y,a.z-b.z),mul=(a,s)=>V(a.x*s,a.y*s,a.z*s),dot=(a,b)=>a.x*b.x+a.y*b.y+a.z*b.z,cross=(a,b)=>V(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x),norm=a=>{const l=Math.hypot(a.x,a.y,a.z)||1;return mul(a,1/l)};let st=C.create(),sel='P1-A',mode='2d',hover=null,paused=false,fog=true,fields=true,reduced=false,queue=[],move=null,acc=0,last=performance.now(),camTween=null;const vis={z:1,px:0,py:0,drag:null},cam={target:{x:15.5,y:8.5,z:0},yaw:D(-35),pitch:D(48),distance:37,fov:D(42)};const unit=()=>st.units.find(u=>u.id===sel)||st.units[0];
function log(t,c=''){const e=document.createElement('div');e.className=c;e.textContent=`[${String(st.tick).padStart(4,'0')}] ${t}`;$('#log').prepend(e)}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1100)}function resize(c){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w||c.height!==h){c.width=w;c.height=h}return{r,d,w,h}}
function fit(c){const m=resize(c),tile=Math.min((m.w-50*m.d)/C.W,(m.h-50*m.d)/C.H)*vis.z,ox=(m.w-tile*C.W)/2+vis.px*m.d,oy=(m.h-tile*C.H)/2+vis.py*m.d;return{...m,tile,ox,oy}}
function renderPos(u){if(!move||move.id!==u.id)return{x:u.x,y:u.y};if(reduced)return move.from;const t=clamp(move.alpha,0,1),e=t*t*(3-2*t);return{x:move.from.x+(move.to.x-move.from.x)*e,y:move.from.y+(move.to.y-move.from.y)*e}}
function draw2(c){const x=c.getContext('2d'),m=fit(c),tm=new Map(st.terrain.map(t=>[C.key(t),t.kind]));x.clearRect(0,0,m.w,m.h);for(let y=0;y<C.H;y++)for(let xx=0;xx<C.W;xx++){x.fillStyle=tm.has(`${xx},${y}`)?'#29483c':((xx+y)%2?'#233443':'#293c4d');x.fillRect(m.ox+xx*m.tile,m.oy+y*m.tile,m.tile,m.tile);x.strokeStyle='#60708055';x.strokeRect(m.ox+xx*m.tile,m.oy+y*m.tile,m.tile,m.tile)}if(fields)for(const f of st.fields){x.fillStyle=f.owner==='p1'?'#4d9eea22':'#d95c6b22';x.beginPath();x.arc(m.ox+(f.x+.5)*m.tile,m.oy+(f.y+.5)*m.tile,f.r*m.tile,0,Math.PI*2);x.fill()}for(const o of st.obstacles){x.fillStyle='#697b84';x.fillRect(m.ox+(o.x+.18)*m.tile,m.oy+(o.y+.18)*m.tile,m.tile*.64,m.tile*.64)}for(const b of st.bases){x.fillStyle=b.playerId==='p1'?'#caa34d':'#ae5362';x.fillRect(m.ox+b.x*m.tile,m.oy+b.y*m.tile,m.tile,m.tile)}if(fog){x.fillStyle='#02060ba8';x.fillRect(m.ox,m.oy,m.tile*2.5,m.tile*C.H);x.fillRect(m.ox+m.tile*28.5,m.oy,m.tile*2.5,m.tile*C.H)}for(const u of st.units){const p=renderPos(u),cx=m.ox+(p.x+.5)*m.tile,cy=m.oy+(p.y+.5)*m.tile,r=m.tile*.3;x.fillStyle=u.playerId==='p1'?'#4d9eea':'#d95c6b';x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.fill();x.strokeStyle=u.id===sel?'#f1d16b':'#fff';x.lineWidth=u.id===sel?3:1.4;x.stroke();x.fillStyle='#fff';x.font=`700 ${Math.max(8,r*.7)}px sans-serif`;x.textAlign='center';x.textBaseline='middle';x.fillText(u.id.slice(-1),cx,cy)}if(hover&&C.inBounds(hover)){x.strokeStyle='#f1d16b';x.lineWidth=2;x.strokeRect(m.ox+hover.x*m.tile,m.oy+hover.y*m.tile,m.tile,m.tile)}}
function basis(c){const m=resize(c),cp=Math.cos(cam.pitch),sp=Math.sin(cam.pitch),cy=Math.cos(cam.yaw),sy=Math.sin(cam.yaw),pos=V(cam.target.x+cam.distance*cp*cy,cam.target.y+cam.distance*cp*sy,cam.target.z+cam.distance*sp),fwd=norm(sub(cam.target,pos)),right=norm(cross(fwd,V(0,0,1))),up=norm(cross(right,fwd)),f=Math.min(m.w,m.h)*.5/Math.tan(cam.fov/2);return{...m,pos,fwd,right,up,f,cx:m.w*.5,cy:m.h*.54}}
function proj(p,b){const q=sub(p,b.pos),z=dot(q,b.fwd);if(z<=.05)return null;return{x:b.cx+dot(q,b.right)*b.f/z,y:b.cy-dot(q,b.up)*b.f/z,z,s:b.f/z}}
function quad(x,y,z,b){return[proj(V(x,y,z),b),proj(V(x+1,y,z),b),proj(V(x+1,y+1,z),b),proj(V(x,y+1,z),b)]}function poly(x,pts,fill,stroke){if(!pts.every(Boolean))return;x.beginPath();x.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>x.lineTo(p.x,p.y));x.closePath();x.fillStyle=fill;x.fill();x.strokeStyle=stroke;x.stroke()}
function draw3(c){const x=c.getContext('2d'),b=basis(c);x.clearRect(0,0,b.w,b.h);const tiles=[];for(let y=0;y<C.H;y++)for(let xx=0;xx<C.W;xx++){const p=proj(V(xx+.5,y+.5,0),b);if(p)tiles.push({x:xx,y,d:p.z})}tiles.sort((a,z)=>z.d-a.d);for(const t of tiles)poly(x,quad(t.x,t.y,0,b),(t.x+t.y)%2?'#223643':'#2a4050','#61788944');if(fields)for(const f of st.fields){const p=proj(V(f.x+.5,f.y+.5,.04),b);if(p){x.fillStyle=f.owner==='p1'?'#4d9eea26':'#d95c6b26';x.beginPath();x.arc(p.x,p.y,Math.max(4,p.s*f.r),0,Math.PI*2);x.fill()}}const objs=[];for(const o of st.obstacles){const p=proj(V(o.x+.5,o.y+.5,.6),b);if(p)objs.push({t:'o',v:o,d:p.z})}for(const ba of st.bases){const p=proj(V(ba.x+.5,ba.y+.5,.6),b);if(p)objs.push({t:'b',v:ba,d:p.z})}for(const u of st.units){const q=renderPos(u),p=proj(V(q.x+.5,q.y+.5,.7),b);if(p)objs.push({t:'u',v:u,q,d:p.z,p})}objs.sort((a,z)=>z.d-a.d);for(const o of objs){if(o.t!=='u'){const p=proj(V(o.v.x+.5,o.v.y+.5,.45),b);if(!p)continue;x.fillStyle=o.t==='b'?(o.v.playerId==='p1'?'#caa34d':'#ae5362'):'#72818a';x.fillRect(p.x-7,p.y-7,14,14);continue}const foot=proj(V(o.q.x+.5,o.q.y+.5,0),b),top=o.p,r=clamp(top.s*.23,5,20);x.strokeStyle='#000b';x.lineWidth=4;x.beginPath();x.moveTo(foot.x,foot.y);x.lineTo(top.x,top.y);x.stroke();x.fillStyle=o.v.playerId==='p1'?'#4d9eea':'#d95c6b';x.beginPath();x.arc(top.x,top.y,r,0,Math.PI*2);x.fill();x.strokeStyle=o.v.id===sel?'#f1d16b':'#fff';x.lineWidth=o.v.id===sel?3:1.3;x.stroke();x.fillStyle='#fff';x.textAlign='center';x.textBaseline='middle';x.font='700 11px sans-serif';x.fillText(o.v.id.slice(-1),top.x,top.y)}if(fog){x.fillStyle='#02060b77';const a=quad(0,0,.02,b),d=quad(28.5,0,.02,b);poly(x,[a[0],a[1],proj(V(2.5,C.H,.02),b),proj(V(0,C.H,.02),b)],'#02060b77','#0000');poly(x,[proj(V(28.5,0,.02),b),proj(V(C.W,0,.02),b),proj(V(C.W,C.H,.02),b),proj(V(28.5,C.H,.02),b)],'#02060b77','#0000')}}
function g2(c,e){const m=fit(c),r=c.getBoundingClientRect(),px=(e.clientX-r.left)*m.d,py=(e.clientY-r.top)*m.d;return{x:Math.floor((px-m.ox)/m.tile),y:Math.floor((py-m.oy)/m.tile)}}function ray(c,e){const b=basis(c),r=c.getBoundingClientRect(),px=(e.clientX-r.left)*b.d,py=(e.clientY-r.top)*b.d,nx=(px-b.cx)/b.f,ny=-(py-b.cy)/b.f,dir=norm(add(b.fwd,add(mul(b.right,nx),mul(b.up,ny))));if(Math.abs(dir.z)<1e-6)return null;const t=-b.pos.z/dir.z;if(t<=0)return null;const h=add(b.pos,mul(dir,t));return{x:Math.floor(h.x),y:Math.floor(h.y)}}
function selectOrMove(g){if(!g||!C.inBounds(g))return;if(move||queue.length)return toast('movimento em execução');const hit=C.at(st,g);if(hit){sel=hit.id;hover=g;log(`selecionado ${hit.id}`);return update()}const p=C.path(st,sel,g);hover=g;if(!p.ok){log(p.reason,'err');return toast(p.reason)}queue=p.path.slice();log(`${sel} → ${g.x},${g.y} · ${p.cost} SPD`);update()}
function desired(u){return{target:{x:u.x+.5,y:u.y+.5,z:.42},yaw:u.playerId==='p1'?Math.PI:0,pitch:D(34),distance:10.5,fov:cam.fov}}function angle(a,b){let d=(b-a)%(Math.PI*2);if(d>Math.PI)d-=Math.PI*2;if(d<-Math.PI)d+=Math.PI*2;return d}function pose(p){cam.target={...p.target};cam.yaw=p.yaw;cam.pitch=p.pitch;cam.distance=p.distance;cam.fov=p.fov??cam.fov;camUI()}function tween(p){if(reduced)return pose(p);camTween={start:performance.now(),dur:430,from:{target:{...cam.target},yaw:cam.yaw,pitch:cam.pitch,distance:cam.distance,fov:cam.fov},to:p,dy:angle(cam.yaw,p.yaw)}}function tweenStep(now){if(!camTween)return;const t=clamp((now-camTween.start)/camTween.dur,0,1),e=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2,a=camTween.from,b=camTween.to;cam.target=V(a.target.x+(b.target.x-a.target.x)*e,a.target.y+(b.target.y-a.target.y)*e,a.target.z+(b.target.z-a.target.z)*e);cam.yaw=a.yaw+camTween.dy*e;cam.pitch=a.pitch+(b.pitch-a.pitch)*e;cam.distance=a.distance+(b.distance-a.distance)*e;if(t>=1){pose(b);camTween=null}else camUI()}
function center2(u){for(const c of [cv.d2,cv.s2])if(c.getBoundingClientRect().width){const m=fit(c),px=m.ox+(u.x+.5)*m.tile,py=m.oy+(u.y+.5)*m.tile;vis.px+=(m.w/2-px)/m.d;vis.py+=(m.h/2-py)/m.d;break}}function focusBehind(u){sel=u.id;center2(u);tween(desired(u));log(`foco atrás de ${u.id}`,'cam');update()}function dbl(c,type,e){const g=type==='2d'?g2(c,e):ray(c,e),u=g&&C.inBounds(g)?C.at(st,g):null;if(u)focusBehind(u);else toast('nenhum monstro')}
function camUI(){$('#yaw').value=Math.round(R(cam.yaw));$('#pitch').value=Math.round(R(cam.pitch));$('#dist').value=Math.round(cam.distance);$('#cam').textContent=`alvo ${cam.target.x.toFixed(1)},${cam.target.y.toFixed(1)} · yaw ${Math.round(R(cam.yaw))}° · elev. ${Math.round(R(cam.pitch))}° · dist. ${cam.distance.toFixed(1)}`}
function update(){$('#sel').textContent=sel;const u=unit();$('#pos').textContent=`${u.x},${u.y}`;$('#spd').textContent=u.spd;$('#hash').textContent=C.hash(st);$('#hover').textContent=hover?`${hover.x},${hover.y}`:'—';if(hover&&C.inBounds(hover)){const p=C.path(st,sel,hover);$('#preview').textContent=p.ok?`${p.cost} SPD`:p.reason}else $('#preview').textContent='—'}
function pointer(c,type,e){return type==='2d'?g2(c,e):ray(c,e)}function attach(c,type){c.addEventListener('pointerdown',e=>{vis.drag={id:e.pointerId,x:e.clientX,y:e.clientY,lx:e.clientX,ly:e.clientY,button:e.button,shift:e.shiftKey,m:false};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{const d=vis.drag;if(d&&d.id===e.pointerId){const dx=e.clientX-d.lx,dy=e.clientY-d.ly;d.lx=e.clientX;d.ly=e.clientY;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>4)d.m=true;if(d.m){if(type==='2d'){vis.px+=dx;vis.py+=dy}else if(d.button===2||d.shift||e.shiftKey){const b=basis(c),s=cam.distance/(Math.min(b.w,b.h)*.9),rg=norm(V(b.right.x,b.right.y,0)),fg=norm(V(b.fwd.x,b.fwd.y,0));cam.target.x+=-dx*s*rg.x+dy*s*fg.x;cam.target.y+=-dx*s*rg.y+dy*s*fg.y;camUI()}else{cam.yaw-=dx*.007;cam.pitch=clamp(cam.pitch+dy*.005,D(20),D(80));camUI()}return}}hover=pointer(c,type,e);update()});c.addEventListener('pointerup',e=>{const d=vis.drag;vis.drag=null;try{c.releasePointerCapture(e.pointerId)}catch{}if(d&&!d.m&&d.button===0)selectOrMove(pointer(c,type,e))});c.addEventListener('dblclick',e=>{e.preventDefault();dbl(c,type,e)});c.addEventListener('contextmenu',e=>e.preventDefault());c.addEventListener('wheel',e=>{e.preventDefault();if(type==='2d')vis.z=clamp(vis.z*(e.deltaY>0?.9:1.1),.5,3.5);else{cam.distance=clamp(cam.distance*(e.deltaY>0?1.08:.92),9,75);camUI()}},{passive:false})}
Object.values(cv).forEach((c,i)=>attach(c,i===0||i===2?'2d':'3d'));
function logic(){if(paused)return;st.tick++;if(!move&&queue.length){const u=unit(),n=queue.shift();move={id:u.id,from:{x:u.x,y:u.y},to:n,n:0,total:C.MOVE_TICKS,alpha:0}}if(move){move.n++;move.alpha=move.n/move.total;if(move.n>=move.total){try{C.step(st,move.id,move.to);log(`${move.id} entrou em ${move.to.x},${move.to.y}`)}catch(e){log(e.message,'err');queue=[]}move=null}}update()}
function frame(now){tweenStep(now);const dt=Math.min(200,now-last);last=now;if(!paused){acc+=dt;while(acc>=C.MS){logic();acc-=C.MS}}if(move&&!paused)move.alpha=clamp((move.n+acc/C.MS)/move.total,0,1);if(mode==='2d')draw2(cv.d2);else if(mode==='3d')draw3(cv.d3);else{draw2(cv.s2);draw3(cv.s3)}requestAnimationFrame(frame)}
function setMode(m){mode=m;$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('#v2d').classList.toggle('active',m==='2d');$('#v3d').classList.toggle('active',m==='3d');$('#vsplit').classList.toggle('active',m==='split');log(`orientação ${m}`,'cam')}
function focus(){const u=unit();camTween=null;cam.target={x:u.x+.5,y:u.y+.5,z:0};center2(u);camUI();log(`foco ${u.id}`,'cam')}function resetCam(){camTween=null;cam.target={x:15.5,y:8.5,z:0};cam.yaw=D(-35);cam.pitch=D(48);cam.distance=37;vis.z=1;vis.px=vis.py=0;camUI()}function reset(){st=C.create();sel='P1-A';hover=null;queue=[];move=null;acc=0;resetCam();update();log('cenário resetado')}
function key(e){if(mode==='2d'||['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;const s=.65*Math.max(.55,cam.distance/37),fg=norm(V(-Math.cos(cam.yaw),-Math.sin(cam.yaw),0)),rg=V(-fg.y,fg.x,0);let ok=true;switch(e.key.toLowerCase()){case'w':cam.target=add(cam.target,mul(fg,s));break;case's':cam.target=add(cam.target,mul(fg,-s));break;case'a':cam.target=add(cam.target,mul(rg,-s));break;case'd':cam.target=add(cam.target,mul(rg,s));break;case'q':cam.yaw-=D(4);break;case'e':cam.yaw+=D(4);break;case'arrowup':cam.pitch=clamp(cam.pitch+D(3),D(20),D(80));break;case'arrowdown':cam.pitch=clamp(cam.pitch-D(3),D(20),D(80));break;case'f':focus();break;case'home':resetCam();break;default:ok=false}if(ok){camUI();e.preventDefault()}}
function tests(){const out=[],t=(n,f)=>{try{f();out.push([n,1])}catch(e){out.push([n,0,e.message])}},a=(x,m='falhou')=>{if(!x)throw Error(m)};
t('mapa 31×17',()=>a(C.W===31&&C.H===17));
t('bases centrais nas extremidades',()=>a(C.BASES[0].x===0&&C.BASES[0].y===8&&C.BASES[1].x===30&&C.BASES[1].y===8));
t('20 Hz / 50 ms',()=>a(C.HZ===20&&C.MS===50));
t('5 monstros por lado',()=>{const s=C.create();a(s.units.filter(u=>u.playerId==='p1').length===5&&s.units.filter(u=>u.playerId==='p2').length===5)});
t('invariantes iniciais',()=>a(!C.valid(C.create()).length));
t('ocupação duplicada é detectada',()=>{const s=C.create();s.units[1].x=s.units[0].x;s.units[1].y=s.units[0].y;a(C.valid(s).includes('ocupação'))});
t('distância ortogonal',()=>a(C.dist({x:1,y:1},{x:2,y:2})===2));
t('hash reproduzível',()=>a(C.hash(C.create())===C.hash(C.create())));
t('câmera fora do hash',()=>{const h=C.hash(st),y=cam.yaw;cam.yaw+=.2;a(C.hash(st)===h);cam.yaw=y});
t('overlays fora do hash',()=>{const h=C.hash(st),f=fog,fd=fields;fog=!fog;fields=!fields;a(C.hash(st)===h);fog=f;fields=fd});
t('redução visual não muda ticks',()=>a(C.MOVE_TICKS===5));
t('foco traseiro p1/p2',()=>{const s=C.create();a(Math.abs(desired(s.units[0]).yaw-Math.PI)<1e-9);a(Math.abs(desired(s.units[5]).yaw)<1e-9)});
t('foco traseiro fora do hash',()=>{const h=C.hash(st),old={target:{...cam.target},yaw:cam.yaw,pitch:cam.pitch,distance:cam.distance,fov:cam.fov};pose(desired(unit()));a(C.hash(st)===h);pose(old)});
t('path cardinal',()=>{const s=C.create(),p=C.path(s,'P1-A',{x:4,y:9});a(p.ok);let q=s.units[0];for(const n of p.path){a(C.dist(q,n)===1);q=n}});
t('custo = quantidade de blocos',()=>{const p=C.path(C.create(),'P1-A',{x:4,y:9});a(p.ok&&p.cost===p.path.length)});
t('base bloqueia destino',()=>a(!C.path(C.create(),'P1-A',{x:0,y:8}).ok));
t('unidade bloqueia destino',()=>a(!C.path(C.create(),'P1-A',{x:5,y:5}).ok));
t('2D/3D/QA compartilham a mesma referência',()=>{const ref=st;setMode('2d');a(st===ref);setMode('3d');a(st===ref);setMode('split');a(st===ref);setMode(mode)});
const pass=out.filter(x=>x[1]).length;$('#tests').innerHTML=`<b>${pass}/${out.length} testes passaram</b>`+out.map(x=>`<div class="${x[1]?'ok':'bad'}">${x[1]?'✓':'✕'} ${x[0]}${x[2]?' — '+x[2]:''}</div>`).join('');$('#tests').classList.add('show');$('#tests').onclick=()=>$('#tests').classList.remove('show');log(`testes ${pass}/${out.length}`,pass===out.length?'cam':'err');return out}
$$('nav button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#focus').onclick=focus;$('#cancel').onclick=()=>{queue=[];move=null};$('#resetCam').onclick=resetCam;$('#preset').onclick=()=>{cam.yaw=D(-35);cam.pitch=D(48);cam.distance=37;camUI()};$('#top').onclick=()=>{cam.yaw=D(-90);cam.pitch=D(80);cam.distance=47;camUI()};$('#reset').onclick=reset;$('#run').onclick=tests;$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'retomar lógica':'pausar lógica'};$('#fog').onchange=e=>fog=e.target.checked;$('#fields').onchange=e=>fields=e.target.checked;$('#reduced').onchange=e=>reduced=e.target.checked;$('#yaw').oninput=e=>{cam.yaw=D(+e.target.value);camUI()};$('#pitch').oninput=e=>{cam.pitch=D(+e.target.value);camUI()};$('#dist').oninput=e=>{cam.distance=+e.target.value;camUI()};document.addEventListener('keydown',e=>{if(e.key==='1')setMode('2d');else if(e.key==='2')setMode('3d');else if(e.key==='3')setMode('split');else key(e)});
window.MIPrototype={getState:()=>C.clone(st),getCamera:()=>C.clone(cam),getVisual:()=>C.clone(vis),setMode,reset,resetCam,tests,desired,focusBehind,project3:(key,x,y)=>{const c=cv[key],b=basis(c),p=proj(V(x+.5,y+.5,0),b),r=c.getBoundingClientRect();return p?{clientX:r.left+p.x/b.d,clientY:r.top+p.y/b.d}:null},project2:(key,x,y)=>{const c=cv[key],m=fit(c),r=c.getBoundingClientRect();return{clientX:r.left+(m.ox+(x+.5)*m.tile)/m.d,clientY:r.top+(m.oy+(y+.5)*m.tile)/m.d}}};camUI();update();log('VIS-002 carregado');requestAnimationFrame(frame)})();
