(()=>{'use strict';const W=31,H=17,HZ=20,MS=50,MOVE_TICKS=5,BASES=[{playerId:'p1',x:0,y:8},{playerId:'p2',x:30,y:8}],N=[{x:1,y:0},{x:0,y:1},{x:-1,y:0},{x:0,y:-1}],clone=x=>JSON.parse(JSON.stringify(x)),key=p=>`${p.x},${p.y}`,inBounds=p=>Number.isInteger(p.x)&&Number.isInteger(p.y)&&p.x>=0&&p.x<W&&p.y>=0&&p.y<H,dist=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
function create(){const terrain=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++)if((x+y)%11===0)terrain.push({x,y,kind:'brush'});return{schema:3,seed:20260929,tick:0,bases:clone(BASES),units:[{id:'P1-A',playerId:'p1',x:3,y:8,hp:8,spd:7},{id:'P1-B',playerId:'p1',x:5,y:5,hp:6,spd:5},{id:'P1-C',playerId:'p1',x:6,y:12,hp:7,spd:6},{id:'P1-D',playerId:'p1',x:9,y:8,hp:9,spd:4},{id:'P1-E',playerId:'p1',x:10,y:14,hp:5,spd:8},{id:'P2-A',playerId:'p2',x:27,y:8,hp:9,spd:6},{id:'P2-B',playerId:'p2',x:25,y:5,hp:7,spd:7},{id:'P2-C',playerId:'p2',x:24,y:12,hp:6,spd:5},{id:'P2-D',playerId:'p2',x:21,y:8,hp:8,spd:4},{id:'P2-E',playerId:'p2',x:20,y:3,hp:5,spd:8}],obstacles:[{x:7,y:4},{x:7,y:5},{x:7,y:6},{x:12,y:10},{x:18,y:7},{x:18,y:8},{x:23,y:11}],terrain,fields:[{id:'a',x:14,y:8,r:2,owner:'p1'},{id:'b',x:17,y:8,r:2,owner:'p2'}]}}
const at=(s,p,except)=>s.units.find(u=>u.id!==except&&u.x===p.x&&u.y===p.y),base=(s,p)=>s.bases.find(b=>b.x===p.x&&b.y===p.y),obs=(s,p)=>s.obstacles.find(o=>o.x===p.x&&o.y===p.y);
function valid(s){const e=[],tiles=new Set(),ids=new Set(),count={p1:0,p2:0};for(const u of s.units){if(!inBounds(u))e.push('fora');if(ids.has(u.id))e.push('id');if(tiles.has(key(u)))e.push('ocupação');if(base(s,u))e.push('base');ids.add(u.id);tiles.add(key(u));count[u.playerId]=(count[u.playerId]||0)+1}if(count.p1>5||count.p2>5)e.push('limite');return e}
function path(s,id,t){const u=s.units.find(x=>x.id===id);if(!u||!inBounds(t)||base(s,t)||obs(s,t)||at(s,t,id))return{ok:false,path:[],reason:'destino ilegal'};const q=[{x:u.x,y:u.y}],prev=new Map([[key(q[0]),null]]);while(q.length){const c=q.shift();if(c.x===t.x&&c.y===t.y)break;for(const d of N){const n={x:c.x+d.x,y:c.y+d.y},k=key(n);if(!inBounds(n)||prev.has(k)||base(s,n)||obs(s,n)||at(s,n,id))continue;prev.set(k,c);q.push(n)}}if(!prev.has(key(t)))return{ok:false,path:[],reason:'sem caminho'};const out=[];let c={...t};while(c.x!==u.x||c.y!==u.y){out.push(c);c=prev.get(key(c))}out.reverse();if(out.length>u.spd)return{ok:false,path:out,reason:'SPD insuficiente'};return{ok:true,path:out,cost:out.length}}
function step(s,id,n){const u=s.units.find(x=>x.id===id);if(!u||dist(u,n)!==1||u.spd<1||base(s,n)||obs(s,n)||at(s,n,id))throw Error('passo ilegal');u.x=n.x;u.y=n.y;u.spd--}
function canonical(s){return{schema:s.schema,seed:s.seed,tick:s.tick,bases:s.bases,units:s.units.map(x=>({...x})).sort((a,b)=>a.id.localeCompare(b.id)),obstacles:s.obstacles,fields:s.fields}}
function hash(s){const str=JSON.stringify(canonical(s));let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
window.MICore=Object.freeze({W,H,HZ,MS,MOVE_TICKS,BASES,N,clone,key,inBounds,dist,create,at,base,obs,valid,path,step,hash})})();
